name: essen-mattress-landing-page
services:
- name: web
  source_dir: /website
  github:
    repo: ESSEN/mattress-landing-page
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: RESEND_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SALES_EMAIL
    value: enquiry@essen.sg
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_WHATSAPP
    value: "6591234567"
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_CALENDLY_URL
    value: "https://calendly.com/enquiry-essen/appointment"
    scope: RUN_AND_BUILD_TIME
  - key: GOOGLE_SHEETS_PRIVATE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_SHEETS_CLIENT_EMAIL
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_SHEETS_SPREADSHEET_ID
    scope: RUN_TIME
    type: SECRET